export const routes: Record<string, string> = {
  //   COVID: "/covid",
  //   COVID_VAX: "/covid-vaccination",
  //   BLOOD_DONATION: "/blood-donation",
  //   ORGAN_DONATION: "/organ-donation",
  //   PEKA_B40: "/peka-b40",
  //   FACILITIES: "/healthcare-facilities",
  //   HOSPITAL_BED: "/hospital-bed-utilisation",
  //   COVIDNOW_DATA: "/covidnow-data",
  KAWASANKU: "/kawasanku",
  LABOUR_MARKET: "/labour-market",
  COMPOSITE_INDEX: "/composite-indices",
  WHOLESALE_RETAIL: "/wholesale-retail-trade",
  INDUSTRIAL_PRODUCTION: "/industrial-production",
  CONSUMER_PRICES: "/consumer-prices",
  PRODUCER_PRICES: "/producer-prices",
  RUBBER: "/rubber",
  CURRENCY_IN_CIRCULATION: "currency-in-circulation",
  MONEY_SUPPLY: "/money-supply",
  RESERVE_MONEY: "/reserve-money",
  INTEREST_RATES: "/interest-rates",
  CRIME: "/violent-property-crime",
  DRUG: "/drug-addiction",
  EXCHANGE_RATE: "/exchange-rates",
} as const;
